site_name: My Docs
dev_addr: 127.0.0.1:8080

nav:
  - Home: index.md
  - Task: task.md
  - Practical 3.1: pract.md
  - Models: models.md
  - Urls: urls.md
  - Views: views.md
  - Serializers: serializers.md
  - Endpoints: endpoints.md

  - Api:
    - "authorization": auth/autorization.md
    - "token authorization": auth/token.md

    - "books list": books/list.md
    - "books info": books/info.md
    - "books create": books/create.md

    - "rooms list": rooms/list.md
    - "rooms info": rooms/info.md
    - "rooms create": rooms/create.md

    - "copys list": copys/list.md
    - "copys info": copys/info.md
    - "copys update": copys/update.md
    - "copys create": copys/create.md

    - "readers list": readers/list.md
    - "readers info": readers/info.md
    - "readers update": readers/update.md
    - "readers create": readers/create.md

    - "authors list": author/list.md
    - "authors info": author/info.md
    - "authors create": author/create.md

    - "book takes list": booktake/list.md
    - "book take info": booktake/info.md
    - "book take create": booktake/create.md

    - "category list": category/list.md
    - "category create": category/create.md

    - "books own by reader": task/show_taken.md
    - "readers that own book more than month": task/taken_last_month.md
    - "books with less 2 copys": task/unique_books.md
    - "readers under_20": task/readers_under_20.md
    - "education percentage": task/education_percentage.md
